import type { Metadata } from "next";
import React from 'react';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import Header from "@/app/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function SignupLayout({ children }: { children: React.ReactNode }) {
    return (
      <div className="flex flex-col h-screen w-screen bg-white">
        <Header />
        <main className="container mx-auto flex flex-1 items-center justify-center">
          <AntdRegistry>
              {children}
          </AntdRegistry>
        </main>
      </div>
    );
  }